# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics

on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 * * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: 'metrics-renders'

      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output_action: commit
          committer_branch: metrics-renders
          committer_message: "chore: update metrics"
          config_timezone: Asia/Taipei
          
          # Options
          filename: metrics.svg
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_discussions: yes
          plugin_discussions_categories_limit: 8