# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics

on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 * * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Switch to output branch
        run: |
          git fetch origin output
          git checkout --orphan output
          git checkout output
          mkdir -p dist

      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: Asia/Taipei

          # Options
          filename: dist/metrics.svg
          template: classic
          base: header, activity, community, repositories, metadata

      - name: Commit and push metrics to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update metrics
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
