# GitHub Action for generating a contribution graph with a snake eating your contributions.
name: Generate snake

# Controls when the action will run.
on:
  schedule:
    # every 12 hours
    - cron: "0 */12 * * *"

  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

  # Also run on every push on the master branch
  push:
    branches:
      - main

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Generate the snake files in './dist/'
        uses: Platane/snk/svg-only@v3
        id: snake-svg
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?color_snake=aqua&palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure the generated file exists
        run: |
          ls dist
          test -f dist/github-snake.svg
          test -f dist/github-snake-dark.svg

      - name: Push new files to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update snake animations
          keep_history: true
          allow_empty_commit: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
